// src/components/quest/QuestionBlock.jsx
const QuestionBlock = ({ question, onAnswerSubmit }) => {
  const [answer, setAnswer] = useState('');

  const handleSubmit = (e) => {
    e.preventDefault();
    if (answer.trim()) {
      onAnswerSubmit(question.id, answer);
      setAnswer('');
    }
  };

  return (
    <div className="question-block">
      <h3>{question.prompt}</h3>
      {/* Question content will contain the "lesson" text generated by Gemini */}
      <div className="lesson-content">{question.content}</div> 
      
      <form onSubmit={handleSubmit}>
        <textarea 
          value={answer} 
          onChange={(e) => setAnswer(e.target.value)} 
          placeholder="Write your solution or answer here..."
        />
        <button type="submit">Submit Answer</button>
      </form>
    </div>
  );
};

export default QuestionBlock;